### ISSUE TITLE
public/items周り

### ISSUE THREAD

**Issue by kinocooper** [hoshigaki-kobo/nagano-cake#40]
- 新着商品(トップページ)に販売停止中の商品が表示されてしまう
- 販売停止中の商品の詳細(show)画面にURL直指定で入れてしまう
- そのままカートにも入れられてしまう(購入できる)

**Comment by Pinaguchi** [comment]
①トップページに販売停止中の商品が表示されてしまう。
解決 => public/homes コントローラーのtopアクションを「＠items = Item.all から @items = Item.where(is_active: true)」に変更。
